name: ESLint Check

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
            node-version: 16
=======
          node-version: 16
>>>>>>> 0b9f1ed562673ef9ed047a13232d356bee7f97de

      - name: npm install
        run: npm ci

      - name: eslint
<<<<<<< HEAD
        run: npm run lint
=======
        run: npm run lint
# force trigger
>>>>>>> 0b9f1ed562673ef9ed047a13232d356bee7f97de
